version: '3'

services:
  app:
    container_name: test
    build: ./
    volumes:
      - ./container_files/logs/gunicorn_error.log:/var/log/gunicorn_error.log
      - ./container_files/logs/uvicorn_error.log:/var/log/uvicorn_error.log
      - ./container_files/logs/gunicorn_access.log:/var/log/gunicorn_access.log
      - ./container_files/logs/uvicorn_access.log:/var/log/uvicorn_access.log
      - ./container_files/data/:/fastapi/app/data/
    ports:
      - "8888:8888"
    command: ./run.sh
