version: '3'

services:
  web_single:
    container_name: serving_patterns_web_single
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_api_iris
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=iris_svc_sklearn.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=4
      - APP_NAME=app.apps.app_web_single
      - PORT=8888
      - PROFILE=0
    ports:
      - "8888:8888"
    command: ./run_api.sh
    depends_on:
      - redis

  synchronous:
    container_name: serving_patterns_synchronous
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_api_iris
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=iris_svc_onnx_runtime.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=4
      - APP_NAME=app.apps.app_synchronous
      - PORT=8889
      - PROFILE=0
    ports:
      - "8889:8889"
    command: ./run_api.sh
    depends_on:
      - redis

  asynchronous:
    container_name: serving_patterns_asynchronous
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_api_iris
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=iris_svc_onnx_runtime.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=4
      - APP_NAME=app.apps.app_asynchronous
      - PORT=8890
      - PROFILE=0
    ports:
      - "8890:8890"
    command: ./run_api.sh
    depends_on:
      - backend
      - redis

  backend:
    container_name: serving_patterns_backend
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_backend_iris
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=iris_svc_onnx_runtime.yaml
      - NUM_PROCS=4
      - BATCH_CODE=app.backend.prediction_batch
      - PROFILE=0
    command: ./run_backend.sh

  web_single_image:
    container_name: serving_patterns_web_single_image
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_api_imagenet_resnet50
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=imagenet_resnet50.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=4
      - APP_NAME=app.apps.app_web_single_image
      - PORT=8891
      - PROFILE=0
    ports:
      - "8891:8891"
    command: ./run_api.sh
    depends_on:
      - redis

  prep_pred_front:
    container_name: serving_patterns_imagenet_inceptionv3_front
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_front_inceptionv3
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=imagenet_inceptionv3.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=4
      - APP_NAME=app.apps.app_prep_pred_image
      - PORT=8892
      - PROFILE=0
    ports:
      - "8892:8892"
    command: ./run_api.sh
    depends_on:
      - redis
      - prep_pred_tfs

  prep_pred_tfs:
    container_name: serving_patterns_imagenet_inceptionv3_tfs
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_tfserving_inceptionv3
    environment:
      - MODEL_NAME=inceptionv3
      - MODEL_BASE_PATH=/models/inceptionv3
    ports:
      - "8500:8500"
      - "8501:8501"

  redis:
    container_name: serving_patterns_redis
    image: "redis:latest"
    ports:
      - "6379:6379"
