version: '3'

services:
  prep_pred_api:
    container_name: serving_patterns_mobilenetv2_api
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_api_mobilenetv2
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=mobilenetv2.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=4
      - APP_NAME=app.apps.app_prep_pred_image
      - PORT=8893
      - TFS_GRPC=prep_pred_tfs:8510
      - PROFILE=0
      - QUEUE_NAME=tfs_queue
    ports:
      - "8893:8893"
    command: ./run_api.sh
    volumes:
      - shared_volume:/shared_volume
    depends_on:
      - redis
      - prep_pred_tfs
      - tfs_backend

  prep_pred_tfs:
    container_name: serving_patterns_mobilenetv2_tfs
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_tfserving_mobilenetv2
    environment:
      - PORT=8510
      - REST_API_PORT=8511
      - MODEL_NAME=mobilenetv2
      - MODEL_BASE_PATH=/models/mobilenetv2
    ports:
      - "8510:8510"
      - "8511:8511"
    entrypoint: ["/usr/bin/tf_serving_entrypoint.sh"]

  tfs_backend:
    container_name: serving_patterns_tfs_backend
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_backend_mobilenetv2
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=mobilenetv2.yaml
      - NUM_PROCS=4
      - BATCH_CODE=app.backend.prediction_batch
      - TFS_GRPC=prep_pred_tfs:8510
      - PROFILE=0
      - PREDICTOR=app.api._predict_image
      - QUEUE_NAME=tfs_queue
    command: ./run_backend.sh
    volumes:
      - shared_volume:/shared_volume
    depends_on:
      - redis

  redis:
    container_name: serving_patterns_redis
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  shared_volume:
    driver_opts:
      type: none
      device: /tmp
      o: bind
