version: '3'

services:
  web_single_image:
    container_name: serving_patterns_image
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_api_resnet50
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=resnet50.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=4
      - APP_NAME=app.apps.app_image
      - PORT=8891
      - PROFILE=0
    ports:
      - "8891:8891"
    command: ./run_api.sh
    depends_on:
      - redis

  redis:
    container_name: serving_patterns_redis
    image: "redis:latest"
    ports:
      - "6379:6379"
