stages:
  prepare_data:
    cmd: python iris_prepare_data.py
    deps:
    - ./data/iris_data.csv
    - ./data/iris_label.csv
    - ./iris_prepare_data.py
    params:
    - prepare_params.yaml:
      - test_rate
    outs:
    - ./data/prepared
  train:
    cmd: python iris_train.py
    deps:
    - ./data/iris_label.csv
    - ./data/prepared/x_train.npy
    - ./data/prepared/y_train.npy
    params:
    - train_params.yaml:
      - ml_model
      - save_format
      - save_model_name
    outs:
    - ./data/trained
  evaluate:
    cmd: python iris_evaluate.py
    deps:
    - ./data/prepared/x_test.npy
    - ./data/prepared/y_test.npy
    params:
    - evaluate_params.yaml:
      - evaluation_model_filename
    outs:
    - ./data/evaluated
