apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-resnet50-tfs
  labels:
    app: api-resnet50-tfs
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: api-resnet50-tfs
  replicas: 2
  template:
    metadata:
      labels:
        app: api-resnet50-tfs
      name: api-resnet50-tfs
    spec:
      containers:
      - name: api-resnet50-tfs
        image: gcr.io/newagent-16e99/github.com/shibuiwilliam/ml-system-in-action/serving_patterns_api_resnet50_tfs:latest
        command: ["./run_api.sh"]
        env:
        - name: PLATFORM
          value: kubernetes
        - name: CACHE_HOST
          value: redis.serving-pattern.svc.cluster.local
        - name: MODEL_INTERFACE
          value: resnet50_tfs.yaml
        - name: GUNICORN_UVICORN
          value: GUNICORN
        - name: WORKERS
          value: "4"
        - name: APP_NAME
          value: "app.apps.app_image:app"
        - name: PORT
          value: "8894"
        - name: PROFILE
          value: "0"
        - name: TFS_GRPC
          value: tfs-resnet50.serving-pattern.svc.cluster.local:8510
        - name: QUEUE_NAME
          value: resnet50_api_queue
        ports:
        - containerPort: 8894
        resources:
          limits:
            cpu: "2"
            memory: "8000Mi"
          requests:
            cpu: "2"
            memory: "8000Mi"
        volumeMounts:
          - name: pvc-nfs
            mountPath: "/mnt"
      volumes:
      - name: pvc-nfs
        persistentVolumeClaim:
          claimName: nfs

---

apiVersion: v1
kind: Service
metadata:
  name: api-resnet50-tfs
  labels:
    app: api-resnet50-tfs
  namespace: serving-pattern
spec:
  ports:
  - port: 8894
    protocol: TCP
  selector:
    app: api-resnet50-tfs
