apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-resnet50
  labels:
    app: api-resnet50
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: api-resnet50
  replicas: 1
  template:
    metadata:
      labels:
        app: api-resnet50
      name: api-resnet50
    spec:
      containers:
      - name: api-resnet50
        image: gcr.io/newagent-16e99/github.com/shibuiwilliam/ml-system-in-action/serving_patterns_api_resnet50:latest
        command: ["./run_api.sh"]
        env:
        - name: PLATFORM
          value: kubernetes
        - name: CACHE_HOST
          value: redis.serving-pattern.svc.cluster.local
        - name: MODEL_INTERFACE
          value: resnet50.yaml
        - name: GUNICORN_UVICORN
          value: GUNICORN
        - name: WORKERS
          value: "4"
        - name: APP_NAME
          value: "app.apps.app_image:app"
        - name: PORT
          value: "8891"
        - name: PROFILE
          value: "0"
        - name: QUEUE_NAME
          value: resnet50_api_queue
        ports:
        - containerPort: 8891
        resources:
          limits:
            cpu: "2"
            memory: "2000Mi"
          requests:
            cpu: "2"
            memory: "2000Mi"
        volumeMounts:
          - name: pvc-nfs
            mountPath: "/mnt"
      volumes:
      - name: pvc-nfs
        persistentVolumeClaim:
          claimName: nfs

---

apiVersion: v1
kind: Service
metadata:
  name: api-resnet50
  labels:
    app: api-resnet50
  namespace: serving-pattern
spec:
  ports:
  - port: 8891
    protocol: TCP
  selector:
    app: api-resnet50
