apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-iris-asynchronous
  labels:
    app: api-iris-asynchronous
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: api-iris-asynchronous
  replicas: 1
  template:
    metadata:
      labels:
        app: api-iris-asynchronous
      name: api-iris-asynchronous
    spec:
      containers:
      - name: api-iris-asynchronous
        image: gcr.io/newagent-16e99/github.com/shibuiwilliam/ml-system-in-action/serving_patterns_api_iris:83e49fb
        command: ["./run_api.sh"]
        env:
        - name: PLATFORM
          value: kubernetes
        - name: CACHE_HOST
          value: redis.serving-pattern.svc.cluster.local
        - name: MODEL_INTERFACE
          value: iris_svc_onnx_runtime.yaml
        - name: GUNICORN_UVICORN
          value: GUNICORN
        - name: WORKERS
          value: "8"
        - name: APP_NAME
          value: "app.apps.app_asynchronous"
        - name: PORT
          value: "8890"
        - name: PROFILE
          value: "0"
        ports:
        - containerPort: 8890

---

apiVersion: v1
kind: Service
metadata:
  name: api-iris-asynchronous
  labels:
    app: api-iris-asynchronous
  namespace: serving-pattern
spec:
  ports:
  - port: 8890
    protocol: TCP
  selector:
    app: api-iris-asynchronous
