apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-iris-synchronous
  labels:
    app: api-iris-synchronous
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: api-iris-synchronous
  replicas: 3
  template:
    metadata:
      labels:
        app: api-iris-synchronous
      name: api-iris-synchronous
    spec:
      containers:
      - name: api-iris-synchronous
        image: gcr.io/newagent-16e99/github.com/shibuiwilliam/ml-system-in-action/serving_patterns_api_iris:latest
        command: ["./run_api.sh"]
        env:
        - name: PLATFORM
          value: kubernetes
        - name: CACHE_HOST
          value: redis.serving-pattern.svc.cluster.local
        - name: MODEL_INTERFACE
          value: iris_tree_onnx_runtime.yaml
        - name: GUNICORN_UVICORN
          value: GUNICORN
        - name: WORKERS
          value: "4"
        - name: BACKLOG
          value: "2048"
        - name: LIMIT_MAX_REQUESTS
          value: "65536"
        - name: MAX_REQUESTS_JITTER
          value: "2048"
        - name: APP_NAME
          value: "src.app.apps.app_synchronous:app"
        - name: PORT
          value: "8889"
        - name: PROFILE
          value: "0"
        - name: QUEUE_NAME
          value: tree_api_queue
        ports:
        - containerPort: 8889
        livenessProbe:
          httpGet:
            port: 8889
            path: /health
          failureThreshold: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8889
            path: /health
          failureThreshold: 2
          periodSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: "1000Mi"
          requests:
            cpu: "2"
            memory: "1000Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: api-iris-synchronous
  labels:
    app: api-iris-synchronous
  namespace: serving-pattern
spec:
  ports:
  - port: 8889
    protocol: TCP
  selector:
    app: api-iris-synchronous
