apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-resnet50-onnx
  labels:
    app: api-resnet50-onnx
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: api-resnet50-onnx
  replicas: 2
  template:
    metadata:
      labels:
        app: api-resnet50-onnx
      name: api-resnet50-onnx
    spec:
      containers:
      - name: api-resnet50-onnx
        image: gcr.io/newagent-16e99/github.com/shibuiwilliam/ml-system-in-action/serving_patterns_api_resnet50_onnx:latest
        command: ["./run_api.sh"]
        env:
        - name: PLATFORM
          value: kubernetes
        - name: CACHE_HOST
          value: redis.serving-pattern.svc.cluster.local
        - name: MODEL_INTERFACE
          value: /serving_patterns/src/app/ml/resnet50_onnx/model/resnet50_onnx.yaml
        - name: RUNNER
          value: GUNICORN
        - name: WORKERS
          value: "16"
        - name: BACKLOG
          value: "32"
        - name: LIMIT_MAX_REQUESTS
          value: "256"
        - name: MAX_REQUESTS_JITTER
          value: "128"
        - name: GRACEFUL_TIMEOUT
          value: "5"
        - name: APP_NAME
          value: "src.app.apps.app_image:app"
        - name: PORT
          value: "8891"
        - name: PROFILE
          value: "1"
        - name: QUEUE_NAME
          value: resnet50_api_queue
        ports:
        - containerPort: 8891
        livenessProbe:
          httpGet:
            port: 8891
            path: /health
          failureThreshold: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8891
            path: /health
          failureThreshold: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: "4"
            memory: "8000Mi"
          requests:
            cpu: "4"
            memory: "8000Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: api-resnet50-onnx
  labels:
    app: api-resnet50-onnx
  namespace: serving-pattern
spec:
  ports:
  - port: 8891
    protocol: TCP
  selector:
    app: api-resnet50-onnx
