apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-iris-web-single
  labels:
    app: api-iris-web-single
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: api-iris-web-single
  replicas: 3
  template:
    metadata:
      labels:
        app: api-iris-web-single
      name: api-iris-web-single
    spec:
      containers:
      - name: api-iris-web-single
        image: gcr.io/newagent-16e99/github.com/shibuiwilliam/ml-system-in-action/serving_patterns_api_iris:latest
        command: ["./run_api.sh"]
        env:
        - name: PLATFORM
          value: kubernetes
        - name: CACHE_HOST
          value: redis.serving-pattern.svc.cluster.local
        - name: MODEL_INTERFACE
          value: iris_svc_sklearn.yaml
        - name: GUNICORN_UVICORN
          value: GUNICORN
        - name: WORKERS
          value: "4"
        - name: BACKLOG
          value: "2048"
        - name: LIMIT_MAX_REQUESTS
          value: "65536"
        - name: MAX_REQUESTS_JITTER
          value: "2048"
        - name: APP_NAME
          value: "src.app.apps.app_web_single:app"
        - name: PORT
          value: "8888"
        - name: PROFILE
          value: "0"
        - name: QUEUE_NAME
          value: svc_api_queue
        resources:
          limits:
            cpu: "2"
            memory: "1000Mi"
          requests:
            cpu: "2"
            memory: "1000Mi"
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: api-iris-web-single
  labels:
    app: api-iris-web-single
  namespace: serving-pattern
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    app: api-iris-web-single
