apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-resnet50-onnx
  labels:
    app: backend-resnet50-onnx
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: backend-resnet50-onnx
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-resnet50-onnx
      name: backend-resnet50-onnx
    spec:
      containers:
      - name: backend-resnet50-onnx
        image: gcr.io/newagent-16e99/github.com/shibuiwilliam/ml-system-in-action/serving_patterns_backend_resnet50_onnx:latest
        command: ["./run_backend.sh"]
        env:
        - name: PLATFORM
          value: kubernetes
        - name: CACHE_HOST
          value: redis.serving-pattern.svc.cluster.local
        - name: MODEL_INTERFACE
          value: resnet50_onnx.yaml
        - name: NUM_PROCS
          value: "2"
        - name: BATCH_CODE
          value: "src.app.backend.prediction_batch"
        - name: PREDICTOR
          value: "src.app.api._predict_image"
        - name: PROFILE
          value: "0"
        - name: QUEUE_NAME
          value: resnet50_api_queue
        resources:
          limits:
            cpu: "2"
            memory: "8000Mi"
          requests:
            cpu: "2"
            memory: "8000Mi"
        volumeMounts:
          - name: pvc-nfs
            mountPath: "/mnt"
      volumes:
      - name: pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
