apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-resnet50-onnx-server
  labels:
    app: backend-resnet50-onnx-server
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: backend-resnet50-onnx-server
  replicas: 3
  template:
    metadata:
      labels:
        app: backend-resnet50-onnx-server
      name: backend-resnet50-onnx-server
    spec:
      containers:
      - name: backend-resnet50-onnx-server
        image: gcr.io/newagent-16e99/github.com/shibuiwilliam/ml-system-in-action/serving_patterns_backend_resnet50_onnx:latest
        command: ["./run_backend.sh"]
        env:
        - name: PLATFORM
          value: kubernetes
        - name: CACHE_HOST
          value: redis.serving-pattern.svc.cluster.local
        - name: MODEL_INTERFACE
          value: /serving_patterns/src/app/ml/resnet50_onnx/model/resnet50_onnx.yaml
        - name: NUM_PROCS
          value: "4"
        - name: BATCH_CODE
          value: "src.app.backend.prediction_batch"
        - name: PREDICTOR
          value: "src.app.api._predict_image"
        - name: PROFILE
          value: "1"
        - name: QUEUE_NAME
          value: resnet50_api_queue
        resources:
          limits:
            cpu: "8"
            memory: "4000Mi"
          requests:
            cpu: "8"
            memory: "4000Mi"
