apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
      name: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          volumeMounts:
            - name: redis-storage
              mountPath: /data/redis
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: serving-pattern
spec:
  ports:
    - port: 6379
      protocol: TCP
  selector:
    app: redis
