version: '3'

services:
  prep_pred_api_mobilenetv2:
    container_name: serving_patterns_prep_pred_api_mobilenetv2
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_api_mobilenetv2
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=mobilenetv2.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=4
      - BACKLOG=64
      - LIMIT_MAX_REQUESTS=1024
      - MAX_REQUESTS_JITTER=128
      - APP_NAME=src.app.apps.app_image:app
      - PORT=8893
      - TFS_GRPC=prep_pred_tfs:8512
      - PROFILE=0
      - QUEUE_NAME=tfs_queue
    ports:
      - "8893:8893"
    command: ./run_api.sh
    volumes:
      - shared_volume:/shared_volume
    depends_on:
      - redis
      - prep_pred_tfs_mobilenetv2
      - prep_pred_backend_mobilenetv2

  prep_pred_tfs_mobilenetv2:
    container_name: serving_patterns_prep_pred_tfs_mobilenetv2
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_tfserving_mobilenetv2
    environment:
      - PORT=8512
      - REST_API_PORT=8513
      - MODEL_NAME=mobilenetv2
      - MODEL_BASE_PATH=/models/mobilenetv2
    ports:
      - "8512:8512"
      - "8513:8513"
    entrypoint: ["/usr/bin/tf_serving_entrypoint.sh"]

  prep_pred_backend_mobilenetv2:
    container_name: serving_patterns_prep_pred_backend_mobilenetv2
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_backend_mobilenetv2
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=mobilenetv2.yaml
      - NUM_PROCS=4
      - BATCH_CODE=src.app.backend.prediction_batch
      - TFS_GRPC=prep_pred_tfs:8512
      - PROFILE=0
      - PREDICTOR=src.app.api._predict_image
      - QUEUE_NAME=tfs_queue
    command: ./run_backend.sh
    volumes:
      - shared_volume:/shared_volume
    depends_on:
      - redis

  redis:
    container_name: serving_patterns_redis
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  shared_volume:
    driver_opts:
      type: none
      device: /tmp
      o: bind
