version: '3'

services:
  proxy_ms_h:
    container_name: serving_patterns_proxy_ms_h
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_proxy
    environment:
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=2
      - BACKLOG=128
      - LIMIT_MAX_REQUESTS=2048
      - MAX_REQUESTS_JITTER=256
      - APP_NAME=src.api_composition_proxy.apps.proxy:app
      - PORT=8000
      - PROFILE=0
      - SERVICE_MOBILENETV2_PLANT=api_mobilenetv2_plant:8895
      - QUEUE_NAME=api_queue
    ports:
      - "8000:8000"
    command: ./run_proxy.sh

  api_mobilenetv2_plant:
    container_name: serving_patterns_api_mobilenetv2_plant
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_api_mobilenetv2_plant
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=mobilenetv2_plant.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=4
      - BACKLOG=64
      - LIMIT_MAX_REQUESTS=1024
      - MAX_REQUESTS_JITTER=128
      - APP_NAME=src.app.apps.app_image:app
      - PORT=8895
      - TFS_GRPC=tfs_mobilenetv2_plant:8514
      - PROFILE=0
      - QUEUE_NAME=tfs_queue
    ports:
      - "8895:8895"
    command: ./run_api.sh
    volumes:
      - shared_volume:/shared_volume
    depends_on:
      - redis
      - tfs_mobilenetv2_plant
      - backend_mobilenetv2_plant

  tfs_mobilenetv2_plant:
    container_name: serving_patterns_tfs_mobilenetv2_plant
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_tfserving_mobilenetv2_plant
    environment:
      - PORT=8514
      - REST_API_PORT=8515
      - MODEL_NAME=mobilenetv2_plant
      - MODEL_BASE_PATH=/models/mobilenetv2_plant
    ports:
      - "8514:8514"
      - "8515:8515"
    entrypoint: ["/usr/bin/tf_serving_entrypoint.sh"]

  backend_mobilenetv2_plant:
    container_name: serving_patterns_backend_mobilenetv2_plant
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_backend_mobilenetv2_plant
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=mobilenetv2_plant.yaml
      - NUM_PROCS=4
      - BATCH_CODE=src.app.backend.prediction_batch
      - TFS_GRPC=tfs_mobilenetv2_plant:8514
      - PROFILE=0
      - PREDICTOR=src.app.api._predict_image
      - QUEUE_NAME=tfs_queue
    command: ./run_backend.sh
    volumes:
      - shared_volume:/shared_volume
    depends_on:
      - redis

  redis:
    container_name: serving_patterns_redis
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  shared_volume:
    driver_opts:
      type: none
      device: /tmp
      o: bind
