version: '3'

services:
  prep_pred_api_resnet50:
    container_name: serving_patterns_prep_pred_api_resnet50
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_api_resnet50_tfs
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=resnet50_tfs.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=4
      - APP_NAME=src.app.apps.app_image:app
      - PORT=8894
      - TFS_GRPC=prep_pred_tfs:8514
      - PROFILE=0
      - QUEUE_NAME=tfs_queue
    ports:
      - "8894:8894"
    command: ./run_api.sh
    volumes:
      - shared_volume:/shared_volume
    depends_on:
      - redis
      - prep_pred_tfs_resnet50
      - prep_pred_backend_resnet50

  prep_pred_tfs_resnet50:
    container_name: serving_patterns_prep_pred_tfs_resnet50
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_tfserving_resnet50
    environment:
      - PORT=8514
      - REST_API_PORT=8515
      - MODEL_NAME=resnet_v2_50
      - MODEL_BASE_PATH=/models/resnet_v2_50
    ports:
      - "8514:8514"
      - "8515:8515"
    entrypoint: ["/usr/bin/tf_serving_entrypoint.sh"]

  prep_pred_backend_resnet50:
    container_name: serving_patterns_prep_pred_backend_resnet50
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_backend_resnet50_tfs
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=resnet50_tfs.yaml
      - NUM_PROCS=4
      - BATCH_CODE=src.app.backend.prediction_batch
      - TFS_GRPC=prep_pred_tfs:8514
      - PROFILE=0
      - PREDICTOR=src.app.api._predict_image
      - QUEUE_NAME=tfs_queue
    command: ./run_backend.sh
    volumes:
      - shared_volume:/shared_volume
    depends_on:
      - redis

  redis:
    container_name: serving_patterns_redis
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  shared_volume:
    driver_opts:
      type: none
      device: /tmp
      o: bind
