version: '3'

services:
  onnx_api_resnet50:
    container_name: onnx_api_resnet50
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_api_resnet50_onnx
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=resnet50_onnx.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=2
      - BACKLOG=16
      - LIMIT_MAX_REQUESTS=128
      - MAX_REQUESTS_JITTER=32
      - APP_NAME=src.app.apps.app_image:app
      - PORT=8891
      - PROFILE=1
      - LOGLEVEL=info
      - QUEUE_NAME=image_queue
    ports:
      - "8891:8891"
    command: ./run_api.sh
    volumes:
      - shared_volume:/shared_volume
    depends_on:
      - redis

  tf_api_resnet50:
    container_name: tf_api_resnet50
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_api_resnet50_tfs
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=resnet50_tfs.yaml
      - GUNICORN_UVICORN=GUNICORN
      - WORKERS=2
      - BACKLOG=16
      - LIMIT_MAX_REQUESTS=128
      - MAX_REQUESTS_JITTER=32
      - APP_NAME=src.app.apps.app_image:app
      - PORT=8894
      - TFS_GRPC=tf_tfs_resnet50:8514
      - PROFILE=1
      - LOGLEVEL=info
      - QUEUE_NAME=tfs_queue
    ports:
      - "8894:8894"
    command: ./run_api.sh
    volumes:
      - shared_volume:/shared_volume
    depends_on:
      - redis
      - tf_tfs_resnet50

  tf_tfs_resnet50:
    container_name: tf_tfs_resnet50
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_tfserving_resnet50
    environment:
      - PORT=8514
      - REST_API_PORT=8515
      - MODEL_NAME=resnet_v2_50
      - MODEL_BASE_PATH=/models/resnet_v2_50
    ports:
      - "8514:8514"
      - "8515:8515"
    entrypoint: ["/usr/bin/tf_serving_entrypoint.sh"]

  load-test-locust:
    container_name: load-test-locust
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_locust
    environment:
      - PLATFORM=docker_compose
      - TARGET_FILE=image_classification_all.py
      - POST_PREDICT_LABEL_RATIO=1
    ports:
      - "8089:8089"
    command: ["locust", "-f", "image_classification_all.py"]

  redis:
    container_name: serving_patterns_redis
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  shared_volume:
    driver_opts:
      type: none
      device: /tmp
      o: bind
